### ISSUE TITLE
Changing the rate of an fn-throttler.

### ISSUE THREAD

**Issue by carlhu** [brunoV/throttler#14]
I have a scenario where initially I want to throttle an `fn-throttler` and rate-initial; and every 5 seconds I have a new maximum rate. Can you offer a suggestion on what the best way to achieve this with fn-throttler is? For example, do we just make a new fn-throttler every 5 seconds?

**Comment by Liath** [comment]
Yeah, I'd just create new ones. Like, if I were to implement some kind of adjustable throttle that's all I would be doing inside this library anyways.

**Comment by carlhu** [comment]
Thanks a lot!
