### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by Limess** [brunoV/throttler#15]
We've noticed the latest clojars release (1.0.0) does not include this fix: https://github.com/brunoV/throttler/pull/3

This has caused us issues with channels not being closed correctly, as we're dynamically creating new instances of `throttle-chan` in our service.

We've forked/released a separate library on Clojars (https://github.com/signal-ai/throttler) with the new source, but would prefer to use the latest of this library and deprecate our fork.

**Comment by liath** [comment]
Done!

**Comment by Limess** [comment]
Thanks a lot!
