### ISSUE TITLE
timing behavior is off in the beginning, more visible with "large" timers

### ISSUE THREAD

**Issue by benfleis** [brunoV/throttler#6]
Dig the library, and love how simple you've made it to use.  

It seems like there's some hiccup in the startup behavior that gets resolved at the 3rd iteration.  I would expect that for at 1 call/s, the minimum number of seconds for N calls is ~N-1, or if you were enforcing the initial period before getting the first token, then ~N.  For the first call, it appears to have a token, and return instantly.  For the second call, it is neither here nor there.  Then at the third, it rounds into form.

I also tried this behavior using `(... 10 :second)`, and saw roughly the same.

Thanks!

```
user=> (def plus-3 (throttler.core/throttle-fn (partial + 3) 1 :second))
#'user/plus-3
user=> (doseq [n (range 12)] (time (println n (map plus-3 (range n)))))
0 ()
"Elapsed time: 0.369 msecs"
1 (3)
"Elapsed time: 0.537 msecs"
2 (3 4)
"Elapsed time: 513.45 msecs"
3 (3 4 5)
"Elapsed time: 3002.501 msecs"
4 (3 4 5 6)
"Elapsed time: 4004.91 msecs"
5 (3 4 5 6 7)
"Elapsed time: 5005.945 msecs"
6 (3 4 5 6 7 8)
"Elapsed time: 6004.004 msecs"
7 (3 4 5 6 7 8 9)
"Elapsed time: 7005.081 msecs"
8 (3 4 5 6 7 8 9 10)
"Elapsed time: 8004.096 msecs"
9 (3 4 5 6 7 8 9 10 11)
"Elapsed time: 9004.347 msecs"
10 (3 4 5 6 7 8 9 10 11 12)
"Elapsed time: 10009.472 msecs"
11 (3 4 5 6 7 8 9 10 11 12 13)
"Elapsed time: 11006.09 msecs"
nil
user=>
```

**Comment by neverfox** [comment]
Yeah, I see the same thing. What I'm really looking for is for the timer to be a maximum, "do not exceed" rate, not a long-term average, because my primary use case is to prevent being hit with rate limit bans on API calls.

**Comment by Liath** [comment]
I think the test is slightly flawed.

Evaluating `(map plus-3 (range n))` at the `0 ()` mark will have `n = 0` so `(range 0)` is yielding an empty collection which means `map` will call `plus-3` 0 times, or rather it doesn't get called at all and so completes instantly.
At the `1 (3)` mark, that `(range 1)` will be a collection with one item so `plus-3` gets called once and the bucket will definitely have a token at this point so it completes instantly.
The `2 (3 4)` is around 2 seconds for me which seems correct so Idk what's up with the `"Elapsed time: 513.45 msecs"` there.
And the rest of the invocations are as expected for both of us. :)

I came to this conclusion by adding some debug output: https://gist.github.com/Liath/f48dd970dcc77e898eb9e77660f36d6d
"+" shows a token being added to the bucket, "-" shows one being consumed, and "." shows how many times the token was used (which should always be one here).
```
user=> (require 'throttler.core) (def plus-3 (throttler.core/throttle-fn (partial + 3) 1 :second)) (doseq [n (range 6)] (time (run! plus-3 (range n))))
nil                               ;; From the (require).
#'user/plus-3                     ;; From the (def).
"Elapsed time: 0.179004 msecs"    ;; Note that the throttled function wasn't called at all
in:(0)                            ;; The fn got called but the bucket will definitely 
-+."Elapsed time: 3.264219 msecs" ;; have a token so this takes no time.
in:(0)                            ;; And now things look correct.
+-.in:(1)
+-."Elapsed time: 1955.265398 msecs"
in:(0)
+-.in:(1)
+-.in:(2)
+-."Elapsed time: 3004.339208 msecs"
in:(0)
+-.in:(1)
+-.in:(2)
+-.in:(3)
+-."Elapsed time: 4003.83316 msecs"
in:(0)
+-.in:(1)
+-.in:(2)
+-.in:(3)
+-.in:(4)
+-."Elapsed time: 5002.860306 msecs"
nil
user=>
```
